version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      - image: brennovich/protobuf-tools
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: build
          command: |
            . venv/bin/activate
            python3 setup.py install
      - run:
          name: test
          command: |
            . venv/bin/activate
            python3 -m unittest discover tests/ "*_test.py"
