version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install codacy-coverage
      - run:
          name: build
          command: |
            . venv/bin/activate
            python3 setup.py sdist bdist_wheel
            python3 setup.py install
          post: |
            mkdir $CIRCLE_ARTIFACTS/dist
            mv dist/* $CIRCLE_ARTIFACTS/dist/.
      - run:
          name: test
          command: |
            . venv/bin/activate
            coverage run setup.py test
            coverage xml
            coverage html
            python-codacy-coverage -r coverage.xml
          post: |
            mkdir $CIRCLE_ARTIFACTS/test
            mv coverage.* $CIRCLE_ARTIFACTS/test/.
